---
  driver:
    name: ec2
    aws_ssh_key_id: kiri-aws
    security_group_ids: ["sg-1a31097d"]
    subnet_id: subnet-b901dae1
    region: us-west-1
    availability_zone: us-west-1c
    require_chef_omnibus: true
    instance_type: t2.micro
    associate_public_ip: true

  provisioner:
  name: chef_zero
  deprecations_as_errors: true
  data_bags_path: "test/fixtures/data_bags"
  cookbook_path: "./cookbooks"

  transport:
  ssh_key: /Users/kiri/.ssh/kiri-aws.pem
  connection_timeout: 10
  connection_retries: 5
  username: ec2-user

  platforms:
    - name: amazonlinux
      driver:
        image_id: ami-3a674d5a
      transport:
        ssh_key: /Users/kiri/.ssh/kiri-aws.pem
        username: ec2-user

  suites:
  - name: client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true


  - name: client-inputs-outputs
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        outputs_conf:
          sslCommonNameToCheck: sslCommonName
          sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
          sslPassword: password
          sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
          sslVerifyServerCert: false
        inputs_conf:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                source: tcp:123123

  - name: client_lwrps
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        accept_license: true
        is_server: false
